services:
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER", "--quiet" ]
      interval: 5s
      timeout: 5s
      retries: 5


  api:
    container_name: api
    build:
      context: .
    ports:
      - "${API_EXTERNAL_PORT}:${API_PORT}"
    command: /bin/sh -c "alembic upgrade head && python src/main.py"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
